spring:
  application:
    name: CONFIG-DEFAULT
  datasource:
    url: jdbc:mysql://localhost:3306/hotelRatingDb2
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    
feign:
    url:
      edge: http://localhost:8761
      rating: http://localhost:8003
      hotel: http://localhost:8002
